### PR TITLE
Look for x-forwarded-proto when building urls

### PR DESCRIPTION
**Pull request by cjellick**
Addresses https://github.com/rancher/rancher/issues/2464

### CODE REVIEW

**Comment by cjellick** [comment]
Note for QA: I did not do a full ELB/HAProxy setup to test this. I tested by making the following requests and ensuring the URLs returned in the cattalog were properly constructed:
```
curl -H 'X-Forwarded-Proto: https' -H 'X-Forwarded-Host: foo' -H 'X-Forwarded-Port: 7777' http://localhost:8080/v1-catalog/templates | jq '.'
curl -H 'X-Forwarded-Proto: https' -H 'Host: foo:7777' http://localhost:8080/v1-catalog/templates | jq '.'
curl -H 'X-Forwarded-Proto: https' -H 'Host: foo' http://localhost:8080/v1-catalog/templates | jq '.'
curl -H 'X-Forwarded-Proto: https' -H 'Host: foo' -H 'X-Forwarded-Port: 7777' http://localhost:8080/v1-catalog/templates | jq '.'
```
Obviously, I was also ensuring that the host and port headers work correctly too.

I make this note just to point out that I did not test it fully with a true ELB, nginx, or haproxy setup and you may want to do that as part of your QA.

**Comment by prachidamle** [comment]
@cjellick code change LGTM. For my curiosity, is the X-Forwarded-Proto header passed by rancher ELB to catalog service? Should I be seeing this header in the requests, if I launch just the rancher-catalog-service locally?

**Comment by cjellick** [comment]
@prachidamle That header is only passed when a proxy in front of rancher sets and passes it. As an example, you can see how we recommend setting up nginx as a proxy and ssl terminator for rancher here:
http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/

**_Warning: convoluted explanation of ELB follows:_**
You mentioned "rancher ELB" which has confused me slightly, so let me clarify that when we say ELB, we are referring to Amazon's elastic loadbalancer service. ELB throws an extra wrinkle the mix because it has to be set up in a special "TCP mode" with [proxy protocol](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html) enabled in order to support websocket connections. When it is setup like that, ELB cannot pass any HTTP headers. So, another proxy needs to sit between rancher and ELB that adds those headers. When running Rancher in a single-server setup, the built in websocket-proxy handles this. When running in a multi-server setup, websocket-proxy doesn't sit in front of rancher and a different proxy (like nginx) must sit in front of each rancher instance and add the X-Forwarded headers.

**Comment by prachidamle** [comment]
@cjellick thanks! the convoluted explanation was helpful. :)

**Comment by alena1108** [comment]
LGTM

**Pull request merged**
