### PR TITLE
Generate UUID for git.rancher.io repositories

### PR DESCRIPTION
**Pull request by LLParse**

### CODE REVIEW

**Comment by vincent99** [comment]
This won't work; the config file on disk gets overwritten by cattle every time the user saves the setting in the API/UI, and then you'll generate a new UUID every time.

It needs to be persisted into the config stored in the DB, or into a separate file that is only read/written by this code.

**Comment by LLParse** [comment]
Ah, didn't know that.

I would agree that setting the UUID in the DB `setting` table would be optimal, but then we would introduce a dependency on rancher. I am inclined to write a separate file with the UUID for simplicity's sake.

**Comment by LLParse** [comment]
Question @vincent99 - when this file is overwritten, is the process stopped and started, or does it receive a HUP signal? I only ask because I noticed a bug in the re-initialization logic which would cause a new goroutine to start refreshing at the configured pollInterval without the old routine ever terminating.

**Comment by LLParse** [comment]
Closing because this service is being rewritten by @joshwget.

**Pull request closed without merging**
