### PR TITLE
Adds maximumRancherVersion

### PR DESCRIPTION
**Pull request by mrajashree**
`maximumRancherVersion` field is added in rancher-compose `.catalog` section. 
https://github.com/rancher/rancher/issues/6073

### CODE REVIEW

**Comment by prachidamle** [comment]
Please add some tests for the new filter

**Comment by mrajashree** [comment]
@prachidamle @vincent99 I've added a test, it fails because qa-catalog doesn't have templates with the field `maximum_rancher_version` and I've submitted PR for that

**Comment by prachidamle** [comment]
code is LGTM

**Comment by vincent99** [comment]
Pls add the tests for variations of min/max/upgradeFrom versions as we talked about on slack.  Also needs rebase.

**Comment by mrajashree** [comment]
@vincent99 yes working on the tests, will add soon

**Pull request merged**
